### ISSUE TITLE
Error with `get_next_node_in_queue_by `

### ISSUE THREAD

**Issue by aaguilarg** [platanus/queue-it#10]
Let's say I have this queue:
```ruby
task = Task.create!(name: 'Example')
task.push_to_queue(User.create!(name: 'Gabriel'))
task.push_to_queue(User.create!(name: 'Leandro'))
task.push_to_queue(User.create!(name: 'Raimundo'))
# Note that the order of the queue is now: [Raimundo's node, Leandro's node, Gabriel's node]
```
Now if I do
```ruby
task. get_next_node_in_queue_by('name', 'Agustin')
```
I'd get this exception: `NoMethodError: undefined method 'nodable' for nil:NilClass`

I'd expect to get something like `nil`

**Comment by GabrielLyonB** [comment]
Hi Agustin! Thank you for the issue. I could not recreate the issue, i receive a `nil` response and that is the expected behaviour.
![imagen](https://user-images.githubusercontent.com/26175977/149516817-23bb184f-91c6-45e0-86a5-5f0caf68f7ef.png)

**Comment by GabrielLyonB** [comment]
Agustín i did found an error when the queue has two nodes:

```ruby
task = Task.create!(name: 'Example')
task.push_to_queue(User.create!(name: 'Gabriel'))
task.push_to_queue(User.create!(name: 'Leandro'))
# Note that the order of the queue is now: [Raimundo's node, Leandro's node, Gabriel's node]
```
If we call `task.get_next_node_in_queue_by('name', 'Agustin')` it was returning the last node. Still not the same problem as yours but thank you anyway.

I also found another problem when the queue has only one node and that actually is the same error that you had.
